import Foundation

struct UniversityData {
    static let llbUniversities = [
        "University of Oxford",
        "University of Cambridge",
        "London School of Economics and Political Science (LSE)",
        "University College London (UCL)",
        "King's College London",
        "University of Edinburgh",
        "Durham University",
        "University of Bristol",
        "University of Manchester",
        "Queen Mary University of London (QMUL)",
        "University of Glasgow",
        "University of York",
        "University of Leeds",
        "University of Birmingham",
        "Aberdeen School of Law",
        "Abertay University",
        "Anglia Ruskin University",
        "Aston University",
        "Birkbeck, University of London",
        "Birmingham City University",
        "Bournemouth University",
        "Brunel University London",
        "Canterbury Christ Church University",
        "City, University of London",
        "Coventry University",
        "De Montfort University",
        "University of Derby",
        "University of Dundee",
        "University of East London",
        "Edinburgh Napier University",
        "Goldsmiths, University of London",
        "Glasgow Caledonian University",
        "University of Greenwich",
        "University of Hertfordshire",
        "Kingston University",
        "Leeds Beckett University",
        "Liverpool Hope University",
        "London Metropolitan University",
        "London South Bank University",
        "Middlesex University",
        "Robert Gordon University",
        "Royal Holloway, University of London",
        "School of Oriental and African Studies (SOAS)",
        "University of Stirling",
        "University of Strathclyde",
        "Ulster University",
        "University of the West of England, Bristol",
        "University of Westminster",
        "University of Wolverhampton",
        "York St John University",
        "Cardiff University",
        "Swansea University",
        "University of Nottingham",
        "University of Warwick",
        "University of Sheffield",
        "University of Southampton",
        "University of Reading",
        "University of Leicester",
        "University of Sussex",
        "University of Surrey",
        "University of Kent",
        "University of Essex",
        "University of East Anglia (UEA)",
        "University of Plymouth",
        "University of Portsmouth",
        "University of Brighton",
        "Oxford Brookes University",
        "Nottingham Trent University",
        "Manchester Metropolitan University",
        "Liverpool John Moores University",
        "Sheffield Hallam University",
        "Northumbria University",
        "University of the West of Scotland",
        "University of South Wales",
        "Bangor University",
        "Aberystwyth University",
        "Queen's University Belfast",
        "The University of Law",
        "BPP University",
        "University of Portsmouth",
        "University of Salford",
        "University of Lincoln",
        "University of Gloucestershire",
        "University of Worcester"
    ].sorted()
}
